#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
# git-prop --- Handle svn-like properties in git

"""

# Copyright © 2014 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
# Created: 2014-02-26
# Last changed: 2014-07-25 14:25:36

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


__author__ = "Sébastien Gross"
__copyright__ = """Copyright © 2014 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>"""

import os, sys, subprocess
import pipes
import json
import argparse

#
# Local classes
#
class Msg:
    """Print messages to the user."""

    INFO = ('\033[95m●', '[I]')
    DEBUG = ('\033[94m✓', '[D]')
    OK = ('\033[92m✔', '[O]')
    WARN = ('\033[93m❢', '[W]')
    ERROR = ('\033[91m✘', '[E]')
    OUT = ('\033[92m', '1>')
    ERR = ('\033[91m', '2>')
    ENDC = '\033[0m'

    @staticmethod
    def __do_print(m, header, stream=sys.stdout, full_color=False):
        if stream.isatty():
            if full_color:
                stream.write(header[0] + m + Msg.ENDC)
            else:
                stream.write(header[0] + Msg.ENDC + ' ' + m)
        else:
            stream.write(header[1] + m)
        stream.write('\n')
        stream.flush()

    @staticmethod
    def ok(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.OK, stream=stream, full_color=full_color)
        
    @staticmethod
    def warn(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.WARN, stream=stream, full_color=full_color)

    @staticmethod
    def debug(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.DEBUG, stream=stream, full_color=full_color)

    @staticmethod
    def error(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.ERROR, stream=stream, full_color=full_color)

    @staticmethod
    def info(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.INFO, stream=stream, full_color=full_color)

    @staticmethod
    def out(m, stream=sys.stdout, full_color=False):
        Msg.__do_print(m, Msg.OUT, stream=stream, full_color=full_color)

    @staticmethod
    def err(m, stream=sys.stderr, full_color=False):
        Msg.__do_print(m, Msg.ERR, stream=stream, full_color=full_color)


properties = {
    'mode': {
        'set': lambda x: int(x, 8),
        'restore': lambda f, x : os.chmod(f, x),
        'dump': lambda x: '%o' % x,
    }
}

def run(cmd, ignore_errors=False):
    """run cmd"""
    proc = subprocess.Popen(cmd,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    proc.wait()
    out, err = proc.communicate()
    rc = proc.returncode
    if rc == 0 or ignore_errors:
        return out
    else:
        sys.stdout.write("Failed (%s): %s\n" %
                         (rc, ' '.join(pipes.quote(arg) for arg in cmd)))
        sys.stderr.write(err)
        sys.exit(1)


def file_in_git(filename):
    "Test if FILENAME is in current git repository."
    ret = [ x for x in run(['git', 'ls-files', filename]).split('\n') if x ]
    return len(ret) == 1
        
def load_data(args):
    """Load ada from file"""
    ret = None
    if os.path.exists(args['data']):
        p = open(args['data'], 'r')
        try:
            ret = json.load(p)
        except ValueError:
            pass
        p.close()
        return ret

def set_property(args):
    """Set properties"""
    data = load_data(args)
    if not data:
        data = {}

    # if property is unknown silently return
    if not properties.has_key(args['propname']):
        return None
    
    fprop = properties[args['propname']]
    add_files = []

    files = args['files']
    if not files:
        files = run(['git', 'ls-files'])
    
    for fn in files:
        fn_root = file_root_relative(fn, args)
        if not file_in_git(fn):
            Msg.warn('%s is not in git. run git add first.' % fn)
            continue
        if not data.has_key(fn_root):
            data[fn_root] = {}
        propv = fprop['set'](args['propvalue'])
        data[fn_root][args['propname']] = fprop['restore'](fn, propv)
        data[fn_root][args['propname']] = propv
        add_files.append(fn_root)

    p = open(args['data'], 'w')
    p.write(json.dumps(data, indent=1))
    p.close()

    run(['git', 'add', args['data']])
    run(['git', 'commit', '-m',
         'git prop set %s %s\n\n - %s' % (
             args['propname'],
             args['propvalue'],
             '\n - '.join(add_files)
         ),
         args['data']], ignore_errors=True)

def delete_property(args):
    "Delete properties"
    data = load_data(args)
    if not data:
        data = {}
    add_files = []

    files = args['files']
    ignore = False
    if not files:
        files = run(['git', 'ls-files']).splitlines()
        ignore = True

    for fn in files:
        fn_root = file_root_relative(fn, args)
        if not data.has_key(fn_root):
            if not ignore:
                Msg.warn('%s has no poperties' % fn)
            continue
        if not data[fn_root].has_key(args['propname']):
            if not ignore:
                Msg.warn('%s has no poperty %s' % (fn, p))
            continue
        del(data[fn_root][args['propname']])
        if not data[fn_root].keys():
            del(data[fn_root])
        add_files.append(fn_root)
        
    p = open(args['data'], 'w')
    p.write(json.dumps(data, indent=1))
    p.close()

    run(['git', 'add', args['data']])
    run(['git', 'commit', '-m',
         'git prop delete %s\n\n - %s' % (
             args['propname'],
             '\n - '.join(add_files)
         ),
         args['data']], ignore_errors=True)

    
    
def restore_property(args):
    """Set properties"""
    data = load_data(args)
    if not data:
        return

    files = args['files']
    if not files:
        files = run(['git', 'ls-files'])

    for fn in files:
        fn_root = file_root_relative(fn, args)
        if not file_in_git(fn_root):
            Msg.warn('%s is not in git any more. You can remove it.' % fn)
            continue
        if not os.path.exists(fn):
            Msg.warn('%s is does not exist. You can remove it.' % fn)
            continue
        if not data.has_key(fn_root):
            Msg.warn('Got no property for %s' % fn)
            continue
        for prop in data[fn_root].keys():
            if not properties.has_key(prop):
                Msg.warn('Invalid property %s for %s' % (prop, fn))
                continue
            properties[prop]['restore'](fn, data[fn_root][prop])
            if args['verbose']:
                Msg.ok('Restoring %s:%s for %s' % (str(prop),
                                                   str(data[fn_root][prop]), fn))


def dump_property(args):
    """Set properties"""
    data = load_data(args)
    files = data.keys()
    files.sort
    for fn in files:
        fn_root = os.path.relpath(os.path.sep.join([args['_root'], fn]),
                                  args['_cwd'])
        sys.stdout.write("%s: " % (fn_root))
        props = data[fn].keys()
        props.sort()
        for p in props:
            sys.stdout.write("%s:%s " % (p, properties[p]['dump'](data[fn][p])))
        sys.stdout.write('\n')
                
def parse_cmd_line():
    """Parse command line arguments"""

    args = argparse.ArgumentParser(
        description='Handle svn-like properties in git',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples: 

  Setting properties:
     git prop set mode 0600 .ssh/id_rsa
     git prop set mode 755 bin/foo

   Restoring properties:
     git prop restore
        '''
    )

    args.add_argument('--data', help='Path to database', metavar='PATH',
                      default='.gitprop')
    args.add_argument('--verbose', '-v', help='Run in verbose mode',
                      action='store_true')

    sp_cmd = args.add_subparsers(help='Command', dest='cmd')
    
    sp_cmd.add_parser('init', help='Setup hooks in .git directory')

    cmd_restore = sp_cmd.add_parser('restore', help='Restore properties')
    cmd_restore.add_argument('files', help='Files', nargs='*')

    
    
    cmd_set = sp_cmd.add_parser('set', help='Set properties')
    cmd_set.add_argument('propname', help='property name', choices=properties.keys() )
    cmd_set.add_argument('propvalue', help='property value')
    cmd_set.add_argument('files', help='Files', nargs='+')

    
    cmd_dump = sp_cmd.add_parser('dump', help='Dump properties')
    cmd_dump.add_argument('files', help='Files', nargs='*')

    cmd_delete = sp_cmd.add_parser('delete', help='Delete properties')
    cmd_delete.add_argument('propname', help='property name',
                            choices=properties.keys() )
    cmd_delete.add_argument('files', help='Files', nargs='*')

    
    ret = args.parse_args().__dict__
    return ret


def get_root():
    "Return the absolute path of git root directory"
    root_dir_list = run(['git', 'rev-parse', '--show-toplevel'],
                        ignore_errors=True).splitlines()
    if not root_dir_list:
        Msg.error('Not in a git repository')
        sys.exit(1)
    return root_dir_list[0]

def file_root_relative(filename, args):
    "Return FILENAME relative to git root directory"
    filename_abs  = os.sep.join([args['_cwd'], filename])
    return root_relative_path(filename_abs, args)



def root_relative_path(file, args):
    return os.path.relpath(
        os.path.abspath(file),
        args['_root'],
    )


def init_hooks(args):
    out = run(['git', 'rev-parse', '--git-dir'])
    dir = out.split('\n')[0]
    f='%s/hooks/post-merge' % dir
    fh = open(f, 'w')
    fh.write( "#!/bin/sh\n\n" +
              "if test -e %s; then\n" % args['data'] +
              "    git prop restore || true\n" +
              "fi\n")
    fh.close()
    os.chmod(f, 33261)
    if not os.path.exists('%s/hooks/post-checkout' % dir):
        os.symlink('post-merge', '%s/hooks/post-checkout' % dir)



def __init__():
    
    args = parse_cmd_line()
    
    args['_cwd'] = os.getcwd()
    args['_root'] = get_root()
    args['_root_rel'] = root_relative_path(os.getcwd(), args)
    
    args['data'] = os.path.relpath(
        os.path.sep.join([args['_root'], args['data']]),
        args['_cwd'])
            
    if args['cmd'] == 'set':
        set_property(args)
    elif args['cmd'] == 'restore':
        restore_property(args)
    elif args['cmd'] == 'dump':
        dump_property(args)
    elif args['cmd'] == 'delete':
        delete_property(args)
    elif args['cmd'] == 'init':
        init_hooks(args)
    
if __name__ == "__main__":
    __init__()
